### ISSUE TITLE
Use registry of the dependency when patching

### ISSUE THREAD

**Issue by teamplayer3** [eopb/cargo-override#146]
## How to reproduce

- Have a dependency from git in Cargo.toml (`<dep> = { git = "<git-repo-url>" }`)
- Adding a patch from local path
- Now it takes the crates-io registry for the patch

## Expected behavior

I think it should use the git URL provided with the dependency for this patch.

```
[patch."<git-repo-url>"]
<dep> = { path = "..." }
```

**Comment by nicopap** [comment]
Well, I was about to submit a new issue, but it would be a duplicate of this one I guess. So here is what I wrote, maybe as reference to future people

As per the [`patch` documentation][p-doc],

> In case the dependency you want to override isn’t loaded from crates.io, you’ll have to change a bit how you use [patch]. For example, if the dependency is a git dependency, you can override it to a local path with:
>
> ```toml
> [patch."https://github.com/your/repository"]
> my-library = { path = "../my-library/path" }
> ```
>
> And that’s it!

[p-doc]: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#overriding-repository-url

This means that if I have a dependency in the form

```toml
my-dependency = { git = "ssh:<my repo>.git", branch = "main" }
```

When I run `cargo override --path ../my-dependency` I should expect the generated `patch` section to look as follow:

```toml
[patch."ssh:<my repo>.git"]
my-dependency = { path = "../my-dependency" }
```

But instead, it produces the following `patch` section:

```toml
[patch.crates-io]
my-dependency = { path = "../my-dependency" }
```

And, `cargo` will never take into account this patch, still pulling the source from `<my repo>`.

I have to add the `--registry  "ssh:<my repo>.git"` flag to my `cargo override` command. But when I do that, it complains with the message seen at line 124 in `lib.rs`. As I explained in #231.

But in any case, `cargo override` should generate the correct patch section.

**Comment by minghu6** [comment]
Confirmed this still reproduces on the latest crates.io release (cargo-override 0.0.8, cargo 1.99.0-nightly).

**Reproduction**

```toml
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
edition = "2024"

[dependencies]
m6parserkit = { git = "https://github.com/minghu6/m6syntax", branch = "bas" }
```

```
$ cargo override --path ../m6syntax/m6parserkit/
Patched dependency "m6parserkit" on registry "crates-io"
```

Resulting manifest:

```toml
[patch.crates-io]
m6parserkit = { path = "/path/to/m6syntax/m6parserkit/" }
```

The patch is then silently ignored by cargo:

```
warning: patch `m6parserkit v0.1.1 (/path/to/m6syntax/m6parserkit)` was not used in the crate graph
  |
  = help: perhaps you meant one of the following:
            https://github.com/minghu6/m6syntax
```

Two problems compound here:

1. The patch is written against `crates-io` instead of the dependency's actual git source, so it is a no-op (this issue).
2. The success message `Patched dependency "m6parserkit" on registry "crates-io"` actively misleads the user into believing the override worked. Detecting that the dependency comes from a git source and either emitting `[patch."<git-url>"]` or failing with a clear error would both fix the UX.
